/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 casual-scott.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/casual-scott.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_aa1ab6c3-6945-4c7e-90a7-f7a17ee456fb'].geometry} material={materials['tripo_mat_aa1ab6c3-6945-4c7e-90a7-f7a17ee456fb']} />
    </group>
  )
}

useGLTF.preload('models/casual-scott.glb')
