/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 formal-scott.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function FormalScottModel(props) {
  const { nodes, materials } = useGLTF('models/formal-scott.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_e7d47d8e-dd50-44d3-8ff8-136340e43c1b'].geometry} material={materials['tripo_mat_e7d47d8e-dd50-44d3-8ff8-136340e43c1b']} />
    </group>
  )
}

useGLTF.preload('models/formal-scott.glb')
