/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 graduation-scott.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/graduation-scott.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_f2bc5d17-379f-4eda-b505-137018bd1459'].geometry} material={materials['tripo_mat_f2bc5d17-379f-4eda-b505-137018bd1459']} />
    </group>
  )
}

useGLTF.preload('models/graduation-scott.glb')
