/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scott-formal.glb -o scott-formal.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/test/scott-formal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_e7d47d8e-dd50-44d3-8ff8-136340e43c1b'].geometry} material={materials['tripo_mat_e7d47d8e-dd50-44d3-8ff8-136340e43c1b']} />
    </group>
  )
}

useGLTF.preload('/test/scott-formal.glb')
